Repository Saplings-Projects/1M_sub, pull requests merged in 2023-12, with the labels that each got.

#13 Added `@Override` comments for children classes that implement a function declared in a parent class
  Buffs/Buff_Poison.gd
  Buffs/Buff_Strength.gd
  Buffs/Buff_Vulnerability.gd
  Buffs/Buff_Weakness.gd
  CONTRIBUTING.md
  Cards/Card_DamageHealth.gd
  Entity/Enemy/Enemy.gd
  Entity/Player/Player.gd
Labels: documentation, enhancement

#8 Implement a github action for future tests with GUT
  .github/workflows/CI.yml
  tests/unit/test_assert_true.gd
Labels: new feature

#16 Add a Status class to be parent of Buff/Debuff
  Buffs/BuffBase.gd
  Buffs/Buff_Poison.gd
  Cards/CardBase.gd
  Cards/Card_DamageHealth.gd
  Cards/Resource/Card_Damage.tres
  Cards/Resource/Card_DamageAll.tres
  Cards/Resource/Card_DamageHealth.tres
  Cards/Resource/Card_EnemyAttack.tres
  Cards/Resource/Card_Heal.tres
  Cards/Resource/Card_Poison.tres
  Core/Battler.gd
  Core/DealDamageData.gd
  Entity/Components/BuffComponent.gd
  Entity/Components/HealthComponent.gd
  Entity/Components/StatusComponent.gd
  Entity/Enemy/Enemy.tscn
  Entity/Entity.gd
  Entity/Player/Player.tscn
  Status/Buffs/BuffBase.gd
  Status/Buffs/Buff_Strength.gd
  Status/Debuffs/DebuffBase.gd
  Status/Debuffs/Debuff_Poison.gd
  Status/Debuffs/Debuff_Vulnerability.gd
  Status/Debuffs/Debuff_Weakness.gd
  Status/StatusBase.gd
  Tests/test_health.gd
Labels: enhancement

#17 Add draw pile and discard pile
  #Scenes/TestingScene.tscn
  ArtSource/Card/discard_pile.aseprite
  ArtSource/Card/draw_pile.aseprite
  Cards/CardBase.gd
  Cards/CardContainer.gd
  Cards/CardContainer.tscn
  Cards/Resource/Card_DrawCards.tres
  Cards/Resource/Card_EnemyAttack.tres
  Cards/Resource/Card_Poison.tres
  Cards/discard_pile.png
  Cards/discard_pile.png.import
  Cards/draw_pile.png
  Cards/draw_pile.png.import
  Core/Battler.gd
  Helpers/StaticHelpers.gd
  Managers/CardManager.gd
  Managers/RandomGenerator.gd
  Tests/test_cards.gd
  UI/CardPileUISetter.gd
  UI/DiscardPileUISetter.gd
  UI/DrawPileUISetter.gd
  project.godot
Labels: new feature

#24 Issue 23: Fix Unit Test CI
  .github/workflows/CI.yml
  CI_test_results.xml
  addons/gut/awaiter.gd
  addons/gut/collected_script.gd
  addons/gut/double_templates/function_template.txt
  addons/gut/double_templates/script_template.txt
  addons/gut/double_tools.gd
  addons/gut/doubler.gd
  addons/gut/gui/GutSceneTheme.tres
  addons/gut/gut_cmdln.gd
  addons/gut/input_sender.gd
  addons/gut/method_maker.gd
  addons/gut/plugin.cfg
  addons/gut/script_parser.gd
  addons/gut/signal_watcher.gd
  addons/gut/source_code_pro.fnt.import
  addons/gut/strutils.gd
  addons/gut/stub_params.gd
  addons/gut/stubber.gd
  addons/gut/test.gd
  addons/gut/utils.gd
Labels: enhancement

#29 Issue 20: Events Structure
  Event/EventBase.gd
  Event/EventHeal.gd
  Event/EventMob.gd
  Event/EventRandom.gd
  Event/EventShop.gd
  Tests/test_eventbase.gd
Labels: new feature

#27 Class structure for the cards
  #Scenes/TestingScene.tscn
  Cards/CardBase.gd
  Cards/Effects/EffectBase.gd
  Cards/Effects/EffectDamage.gd
  Cards/Effects/EffectDamageHealth.gd
  Cards/Effects/EffectData.gd
  Cards/Effects/EffectDiscardRandom.gd
  Cards/Effects/EffectDraw.gd
  Cards/Effects/EffectPoison.gd
  Cards/Resource/Card_Damage.tres
  Cards/Resource/Card_DamageHealth.tres
  Cards/Resource/Card_DrawCards.tres
  Cards/Resource/Card_Poison.tres
  Cards/Resource/Card_damage_and_poison.tres
  Core/Battler.gd
  Entity/Components/BehaviorComponent.gd
  Tests/test_cards.gd
  addons/gut/gui/GutSceneTheme.tres
Labels: new feature

#25 Deck animation and layout
  #Scenes/TestingScene.tscn
  Cards/Card.tscn
  Cards/CardBase.gd
  Cards/CardContainer.gd
  Cards/CardContainer.tscn
  Cards/CardMovementComponent.gd
  Cards/CardWorld.gd
  Cards/Movement State/CardMovementState.gd
  Cards/Movement State/CardStateProperties.gd
  Cards/Movement State/MoveState_Discarding.gd
  Cards/Movement State/MoveState_Hovered.gd
  Cards/Movement State/MoveState_InHand.gd
  Cards/Movement State/MoveState_MovingToHand.gd
  Cards/Movement State/MoveState_Queued.gd
  Cards/Resource/Card_Damage.tres
  Cards/Resource/Card_DamageHealth.tres
  Cards/Resource/Card_DrawCards.tres
  Cards/Resource/Card_Poison.tres
  Cards/Resource/Card_damage_and_poison.tres
  Core/Battler.gd
  Core/Enums.gd
  Helpers/EasingConstants.gd
  Helpers/StaticHelpers.gd
  Managers/CardManager.gd
  Tests/test_cards.gd
  Tests/test_health.gd
  UI/EndTurnButton.gd
Labels: new feature
